# Site setings
name: 'HONGTANI'
description: 'Digital Marketer'
meta_description: '디지털마케팅 기초 강의와 GA 세팅까지'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "안녕하세요, 디지털마케터 Hongtani의 블로그입니다."
favicon: 'assets/images/favicon.ico'
baseurl: 'http://hongtani.com'
production_url: https://hongtani.com/
disqus: 'hongtani'
mailchimp_url: '//hongtani.us5.list-manage.com/subscribe/post?u=d6e9edd33e0c04cb22fe59a1f&amp;id=9889a03d62'
# Add your GA Tracking Id
ga_analytics:

# Contact form setings
email: hongtani625@gmail.com
contact_page_description: "궁금하신 부분이나 문의하실 내용은 아래 양식에 맞춰 작성하여 전달 부탁드립니다."
thankyou_page_description: "작성이 완료되었습니다. 메일은 확인하는 대로 답장 드리겠습니다. 감사합니다!"

# Social links
facebook: '/groups/291919502455468'
#github: 'justgoodthemes'
#codepen: 'username'
#dribbble: 'username'
#medium: '@username'
instagram: 'hongxha'
#pinterest: 'username'
#linkedin: 'username'
#producthunt: '@username'
#quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog Guide
    url: /blog-guide
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
